# Conformal prediction configuration for training evaluation
conformal:
  # Global settings
  method: split_conformal
  calibration_split: 0.2  # Fraction of dev set for calibration
  
  # Risk targets for evaluation
  global:
    max_error_rate: 0.01  # 1% maximum error rate
    min_coverage: 0.85  # 85% minimum coverage
    
  # Per-slice overrides for critical evaluation
  per_slice:
    medical_domain:
      max_error_rate: 0.005
      min_coverage: 0.9