# Slice definitions for fine-grained evaluation
slices:
  - name: short_text
    description: "Text with fewer than 100 tokens"
    condition:
      type: length
      max_tokens: 100
      
  - name: long_text
    description: "Text with more than 1000 tokens"
    condition:
      type: length
      min_tokens: 1000
      
  - name: high_negation
    description: "Text with high negation density"
    condition:
      type: pattern
      regex: "\\b(not|no|never|neither|none|nothing|nowhere|nobody)\\b"
      min_matches: 3
      
  - name: medical_domain
    description: "Medical/clinical domain text"
    condition:
      type: keyword_density
      keywords:
        - patient
        - symptoms
        - treatment
        - diagnosis
        - clinical
        - virus
        - infection
      min_density: 0.02
      
  - name: research_paper
    description: "Academic research paper format"
    condition:
      type: pattern
      regex: "(abstract|introduction|methods|results|discussion|conclusion)"
      case_insensitive: true
      
  - name: news_article
    description: "News article format"
    condition:
      type: metadata
      field: source
      values: ["news", "media", "press"]
      
  - name: social_media
    description: "Social media posts"
    condition:
      type: metadata
      field: source
      values: ["twitter", "facebook", "reddit"]
      
  - name: high_uncertainty
    description: "Text with uncertainty markers"
    condition:
      type: pattern
      regex: "\\b(may|might|could|possibly|potentially|perhaps|unclear|unknown)\\b"
      min_matches: 2

# Slice importance weights for worst-case evaluation
slice_weights:
  medical_domain: 2.0
  research_paper: 1.5
  high_uncertainty: 1.3
  default: 1.0