# GitHub Actions workflow for testing DSL rules
name: DSL Rule Tests

on:
  push:
    paths:
      - 'dsl/**'
      - 'tests/test_dsl.py'
  pull_request:
    paths:
      - 'dsl/**'
      - 'tests/test_dsl.py'

jobs:
  test-rules:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        pip install -e .
        pip install pytest pytest-cov
    
    - name: Validate DSL rules YAML
      run: |
        python -c "
        import yaml
        with open('dsl/rules.yaml') as f:
            rules = yaml.safe_load(f)
        print(f'Loaded {len(rules.get(\"rules\", []))} rules')
        "
    
    - name: Run DSL tests
      run: |
        pytest tests/test_dsl.py -v --cov=dsl --cov-report=xml
    
    - name: Check rule coverage
      run: |
        python scripts/check_rule_coverage.py
    
    - name: Upload coverage
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        flags: dsl-tests